### ISSUE TITLE
monte_DM not behaving as expected

### ISSUE THREAD

**Issue by xiggystardust** [FRBs/FRB#55]
I've been trying to use the monte_DM function to generate random DMs at a few redshifts, but the DMs it gives me always return values close to zero (and almost always less than one, unless I give it an input z that is >>1000). I can't tell if I'm misinterpreting the required inputs or the function is not behaving as it should, but I suspect the latter.

Exaggerated example:

`zeval = np.array([5000000.])
DMs = dlas.monte_DM(np.array(zeval),nrand=10,verbose=True)
print (DMs)

[[1.88271587]
 [1.76830048]
 [1.62246317]
 [2.01077118]
 [1.6854759 ]
 [1.58467326]
 [2.06783712]
 [1.80738986]
 [1.97811124]
 [1.9119804 ]]`

**Comment by xiggystardust** [comment]
More sane example:
`>>> zeval = np.array([1.,2.])
>>> DMs = dlas.monte_DM(np.array(zeval),nrand=10,verbose=True)
>>> print(DMs)
[[0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.        ]
 [0.         0.13121706]
 [0.         0.        ]
 [0.17333167 0.        ]
 [0.13205262 0.        ]]`

**Comment by JunTian-CIRA** [comment]
I'm having the same issue as well.

**Comment by profxj** [comment]
Consider the `monte_DM()` method to be deprecated.

See the new methods in `prob_dmz.py` in the `macquart_relation` but
note these are under construction..
