### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by grx40** [FRBs/FRB#72]
I'm getting a syntax error when trying to install it: 
`  File "/Users/michael/miniconda2/lib/python2.7/site-packages/FRB-0.1.dev0-py2.7.egg/frb/galaxies/galfit.py", line 29
    def get_platescale(wcs:WCS)->float:`

Is there something obvious that I'm overlooking?

**Comment by SunilSimha** [comment]
Hello! This code has been written with python 3. I notice that you're using 2.7. Can you try switching to 3 (>3. should be ideal) and let us know if the problem persists?

**Comment by grx40** [comment]
That was the issue. It works fine now. Should have picked up on that. Thanks!
